### ISSUE TITLE
Please do not map h and l in the floating window

### ISSUE THREAD

**Issue by wookayin** [rhysd/git-messenger.vim#3]
In commit f6fa25a3a546730d0ca6ed68ccf31ed696d0b3a0, new keybindings are added: `h` and `l` for browsing prev/next commit on the line. This feature is so nice, but I feel the default keybinding is somewhat unnatural to me as `h` and `l` are also the keys for cursor movement. Please consider switching to another keys by default.

It would be also great to have those keymaps configurable, using `<Plug>` mappings.

**Comment by rhysd** [comment]
I thought `h` and `l` were fine since in popup window `wrap` is set and no editing happens so they would be never used. However, when a user wants to yank some text in the window, overwriting `h` or `l` may be inconvenient.

OK, I'll reconsider the mappings. If you have some recommendations, please let me know.

> It would be also great to have those keymaps configurable, using <Plug> mappings.

It would be great but a bit complicated since they are buffer local mappings. I think a user don't always define these mappings since they are effective only in popup window. We need to provide some hook functions user can define to make some keymap definitions in popup window.

**Comment by rhysd** [comment]
I'm considering `o` for going back (**o**lder) since `o` is a mapping to enter insert mode and it is never used in popup window. Also considering going forward to `O` like `f` and `F`.

What do you think?

**Comment by wookayin** [comment]
Thanks for your feedback. Actually I was thinking of `Ctrl-O` and `Ctrl-I` as they are keys for jumping to older/new cursor position in 'jumplist' (but not super sure which one would be the best). But `o` and `O` look reasonable too.

**Comment by rhysd** [comment]
Thank you for the suggestion. It also seems reasonable. I think I should add the functionality to map these mappings by user.

**Comment by wookayin** [comment]
I find the keys `<C-O>` `<C-I>` in the popup window work pretty annoyingly (it would just show the source code buffers...), no reason to not map these keys to older/Older jumping. I managed to make it like:

```
au FileType gitmessengerpopup nmap <C-O> o
au FileType gitmessengerpopup nmap <C-I> O
```

which works as expected. Hope this can be useful for someone who find this on the web.

**Comment by rhysd** [comment]
Actually it's a bug of git-messenger.vim (it should close popup when its buffer is switched). For now, your configuration is a good way to avoid the issue.
