### ISSUE TITLE
REQ: Enter key moves cursor into the window

### ISSUE THREAD

**Issue by butterflyfish** [rhysd/git-messenger.vim#34]
When a popup window is already open, it moves cursor into the window.

**Comment by rhysd** [comment]
`<CR>` is a very common key sequence used by other plugins or user keymaps. So overwriting it sounds not good idea for me. Isn't inputting keymap for `:GitMessenger` twice sufficient for you?

**Comment by butterflyfish** [comment]
only map <CR> when floating window is already open and cursor is out of floating window.

> Isn't inputting keymap for :GitMessenger twice sufficient for you?
It's a good idea, but key map is not very short. <leader>gm trigger :GitMessenger.

If it's not easy to do or have side effect, you can close this ticket.

**Comment by rhysd** [comment]
I'm sorry for the delay. I considered how to implement this. As far as I know, there is no solid way to restore mapping. There is no API to save/restore mapping. So, I think we need to use output from `:nmap` and parse it.

```vim
let output = execute('nmap <CR>')
nnoremap <CR> :<C-u>GitMessenger<CR>

" When popup is closed
let mapping = ParseNmapOutput(output)
execute 'nnoremap <CR>' mapping
```

It is hard to implement `ParseNmapOutput()` in terms of following points:

- There is no way to check special character in output. For example, if we see `<CR>` in output, There is no way to understand it is actual sequence `"<CR>"` or special sequence `"\<CR>"`. We can understand the `<CR>` is special sequence since it is colored in output of `:nmap`, but `execute()` function omits color information from command output.
- Format of output of `:nmap` is not defined anywhere. It may be changed in the future
- We need to handle the case where no mapping is defined

**Comment by butterflyfish** [comment]
whatever, thank you for your response. please allow me to close this ticket.
