### ISSUE TITLE
It's a very nice plugin!

### ISSUE THREAD

**Issue by kdurant** [rhysd/git-messenger.vim#4]
Thanks for you job, very good!

I hope to see more features!

**Comment by rhysd** [comment]
😄 If you have some feature requests and/or bugs, please feel free to make issues for them (though I'm not able to promise to implement them).
And pull requests are more than welcome, of course.

**Comment by ranelpadon** [comment]
@rhysd Thanks for this awesome plugin! This is a great complement or alternative to [git-blame.nvim](https://github.com/f-person/git-blame.nvim#commands):
- **git-blame.nvim** : open the commit diff in browser (via `:GitBlameOpenCommitURL`)
- **git-messenger.vim**: open the commit diff in Vim's popup

**git-messenger.vim** is more efficient since it's integrated into Vim itself. **git-blame.nvim** is useful though if you want to share with your colleague the commit link for discussion purposes. Cheers. :)
